//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciBilgiSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ders()
        {
            this.Ogretmen_Ogrenci_Ders = new HashSet<Ogretmen_Ogrenci_Ders>();
        }
    
        public int DersId { get; set; }
        public string DersAdi { get; set; }
        public string DersKodu { get; set; }
        public Nullable<int> Kredi { get; set; }
        public Nullable<int> BolumId { get; set; }
        public Nullable<short> AktifPasif { get; set; }
    
        public virtual Bolum Bolum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ogretmen_Ogrenci_Ders> Ogretmen_Ogrenci_Ders { get; set; }
    }
}
