//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciBilgiSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogretmen_Ogrenci_Ders
    {
        public int Ogretmen_Ogrenci_DersID { get; set; }
        public Nullable<int> Ogrt_Ogr_ID { get; set; }
        public Nullable<int> DersID { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Vize1 { get; set; }
        public Nullable<int> Vize2 { get; set; }
        public Nullable<int> Final { get; set; }
    
        public virtual Ders Ders { get; set; }
        public virtual Ogretmen Ogretmen { get; set; }
    }
}
